name: Auto Comment on Issues

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Add comment based on label
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.issue;
            const labels = issue.labels.map(label => label.name);
            let commentBody = '';
            
            if (labels.includes('bug')) {
              commentBody = 'Thank you. We will fix it';
            } else if (labels.includes('feature')) {
              commentBody = 'Thank you, we will consider to include this feature.';
            } else {
              commentBody = 'Thank you for your contribution!';
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: commentBody
            });